resources:
  repositories:
    - repository: templates
      type: git
      name: SRE/HIAE.SRE.Templates
      ref: refs/heads/master
stages:
- template: catalog/openshift-angular-v4.yml@templates
trigger:
- develop*
- hotfix
- fortify